# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 83b049d8bdf7cda3722388c44de1f9a280ef8d33fcb53e475f01a45557e413172575acac4ff0fad511c27fe98adc4575e460c5f33fd229cddecef582681510fd

test:
  secret_key_base: 37775a4d7ef9fe88a864d53e5b168d8db46e1564a227326cb597ee05e97eb675b2a8cba40330216e70fce51f9af8399e08785eccd4a335346910ff40fab9981f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
